/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/Card.vue')['default']
    Chapters: typeof import('./src/components/Chapters.vue')['default']
    Comments: typeof import('./src/components/Comments.vue')['default']
    Container: typeof import('./src/components/Container.vue')['default']
    DefaultFooter: typeof import('./src/components/DefaultFooter.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    FreeSwiper: typeof import('./src/components/FreeSwiper.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    'IBi:sinaWeibo': typeof import('~icons/bi/sina-weibo')['default']
    IconEpFold: typeof import('~icons/ep/fold')['default']
    IEpAdjustContrast: typeof import('~icons/ep/adjust-contrast')['default']
    IEpFold: typeof import('~icons/ep/fold')['default']
    'IIc:baselineWechat': typeof import('~icons/ic/baseline-wechat')['default']
    IIcRoundMenu: typeof import('~icons/ic/round-menu')['default']
    IMdiAccount: typeof import('~icons/mdi/account')['default']
    IMdiArrowLeftThin: typeof import('~icons/mdi/arrow-left-thin')['default']
    IMdiArrowRightThin: typeof import('~icons/mdi/arrow-right-thin')['default']
    'IRadixIcons:cross2': typeof import('~icons/radix-icons/cross2')['default']
    MdiAccount: typeof import('~icons/mdi/account')['default']
    MemberBenefits: typeof import('./src/components/MemberBenefits.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    MobileNavbar: typeof import('./src/components/MobileNavbar.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    ReloadPrompt: typeof import('./src/components/ReloadPrompt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Swiper: typeof import('./src/components/Swiper.vue')['default']
    Toast: typeof import('./src/components/Toast.vue')['default']
  }
}
